# Generated by Django 5.2.4 on 2026-05-25 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-created_at', '-id'), 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
