APP_VERBOSE_NAME_PROJECTS = "Управление проектами"
APP_VERBOSE_NAME_USERS = "Управление пользователями"
AVATAR_CANVAS_SIZE = 256
AVATAR_COLOR_AMBER = "#F59E0B"
AVATAR_COLOR_BLUE = "#3B82F6"
AVATAR_COLOR_EMERALD = "#10B981"
AVATAR_COLOR_PURPLE = "#8B5CF6"
AVATAR_COLOR_RED = "#EF4444"
AVATAR_COLOR_TEAL = "#14B8A6"
AVATAR_FONT_SIZE_RATIO = 0.5625
AVATAR_COLORS = (
    AVATAR_COLOR_AMBER,
    AVATAR_COLOR_RED,
    AVATAR_COLOR_EMERALD,
    AVATAR_COLOR_BLUE,
    AVATAR_COLOR_PURPLE,
    AVATAR_COLOR_TEAL,
)
AVATAR_TEXT_COLOR = "#FFFFFF"
AVATAR_TEXT_VERTICAL_OFFSET_RATIO = 0.046875
DEFAULT_PAGINATION_PER_PAGE = 12
FIELD_VERBOSE_NAME_ABOUT = "О себе"
FIELD_VERBOSE_NAME_AUTHOR = "Автор проекта"
FIELD_VERBOSE_NAME_CREATED_AT = "Дата создания"
FIELD_VERBOSE_NAME_DESCRIPTION = "Описание"
FIELD_VERBOSE_NAME_EMAIL = "Email"
FIELD_VERBOSE_NAME_FAVORITES = "Избранные проекты"
FIELD_VERBOSE_NAME_GITHUB = "GitHub"
FIELD_VERBOSE_NAME_IS_ACTIVE = "Активен"
FIELD_VERBOSE_NAME_IS_STAFF = "Администратор"
FIELD_VERBOSE_NAME_NAME = "Имя"
FIELD_VERBOSE_NAME_PARTICIPANTS = "Участники"
FIELD_VERBOSE_NAME_PHONE = "Телефон"
FIELD_VERBOSE_NAME_PROJECT_NAME = "Название"
FIELD_VERBOSE_NAME_STATUS = "Статус"
FIELD_VERBOSE_NAME_SURNAME = "Фамилия"
FIELD_VERBOSE_NAME_AVATAR = "Аватар"
MODEL_VERBOSE_NAME_PROJECT = "Проект"
MODEL_VERBOSE_NAME_PROJECTS = "Проекты"
MODEL_VERBOSE_NAME_USER = "Пользователь"
MODEL_VERBOSE_NAME_USERS = "Пользователи"
PROJECT_NAME_MAX_LENGTH = 200
PROJECT_STATUS_MAX_LENGTH = 6
USER_ABOUT_MAX_LENGTH = 256
USER_NAME_MAX_LENGTH = 124
USER_PHONE_MAX_LENGTH = 12
